### ISSUE TITLE
Can settings be stored in misc.xml?

### ISSUE THREAD

**Issue by breandan** [JetBrains/embeddedProjectJdk#3]
Under `File | Project Structure | Project SDK`, if you configure a project specific SDK, it places an XML file into `.idea` that contains something like the following:

```
<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="ProjectRootManager" version="2" languageLevel="JDK_1_8" default="false" project-jdk-name="1.8 (1)" project-jdk-type="JavaSDK">
    <output url="file://$PROJECT_DIR$/classes" />
  </component>
</project>
```

Maybe this existing mechanism can be used to store the JDK path, overriding `jdk.table.xml`?

**Comment by mfilippov** [comment]
misc.xml stores only JDK Id and it is not connected with JDK sharing mechanism. JDK Id should match with Id from JDK table.
