### ISSUE TITLE
Auto-detection of local Java Development Kits

### ISSUE THREAD

**Issue by breandan** [JetBrains/embeddedProjectJdk#4]
Maybe there is a way to walk the common places where JDKs are installed to automatically detect all the available JDKs on the system.

**Comment by BorzdeG** [comment]
@breandan If not against, I would implement this functionality in the [Jvm Wrapper plugin](https://github.com/itbasis/jvm-wrapper-ide-plugins)

**Comment by mfilippov** [comment]
@breandan Thank you for the feedback. The main IDEA of this plugin it allows put JDK into a project. I think this is request out of scope.

**Comment by BorzdeG** [comment]
@breandan see https://github.com/itbasis/jvm-wrapper-ide-plugins/issues/3
