### ISSUE TITLE
Merge this project with gradle-idea-ext-plugin?

### ISSUE THREAD

**Issue by breandan** [JetBrains/embeddedProjectJdk#6]
Seems like both could projects could benefit by merging efforts.

https://github.com/JetBrains/gradle-idea-ext-plugin

@nskvortsov

**Comment by nskvortsov** [comment]
This is an Intellij Plugin, I do not think merging it is a good idea. But `idea-ext` plugin definitely could allow to store project JDK definitions: it is already requested at https://github.com/JetBrains/gradle-idea-ext-plugin/issues/25

**Comment by mfilippov** [comment]
@breandan I agree with @nskvortsov. The main target of this project adds a way to sync JDK options when JDK bundled with the project.
